#!/bin/bash


# Start all containers.

docker-compose -f meta-security-core.yml up -d

# docker-compose -f meta-security-core.yml down; sleep 10; docker-compose -f meta-security-core.yml up -d; sleep 10; docker-compose -f meta-security-core.yml  logs --tail 100 -f