##############################################################
#
#    calls to core
#
##############################################################
###   add the db
PUT http://localhost:8080/v1airr

###

###   add the rearrangement_0 collection
PUT http://localhost:8080/v1airr/rearrangement_0

###

###  we want to check that PUT new name collection w/o document creates new collection
#
PUT http://localhost:8080/v1airr/rearrangement_0
Content-Type: application/json
###  201
# running the above a second time removes the aggrs value from properties


###  we want to check that PUT new name collection with document creates new document in collection?
#
PUT http://localhost:8080/v1airr/rearrangement_0
Content-Type: application/json

{ "aggrs" : [
  {
    "stages": [
      { "$match": { "$var":"match" } },
      { "$group": { "_id": { "$var":"field" }, "count": { "$sum": 1}}}
    ],
    "type":"pipeline",
    "uri":"tst3facets"
  }
]
}

###   creates aggrs property returns a 200

###  we want to check that PATCH existing collection with property aggrs creates modifies aggrs
#
PATCH http://localhost:8080/v1airr/rearrangement_0
Content-Type: application/json

{ "aggrs" : [
  {
    "stages": [
      { "$match": { "$var":"match" } },
      { "$group": { "_id": { "$var":"field" }, "count": { "$sum": 1}}}
    ],
    "type":"pipeline",
    "uri":"tst5facets"
  },
  {
    "stages": [
      { "$match": { "$var":"match" } },
      { "$group": { "_id": { "$var":"field" }, "count": { "$sum": 1}}}
    ],
    "type":"pipeline",
    "uri":"tst2facets"
  }
]
}

###   creates aggrs property returns a 200

##############################################################
#
#    calls to security
#
##############################################################

###   add the db
GET http://localhost:8199/meta/v3/v1airr
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

###

###   add the rearrangement_0 collection
GET http://localhost:8199/meta/v3/v1airr/rearrangement_0/_meta
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

###



