# curl -H "Authorization:Bearer $tok"  https://vdj-agave-api.tacc.utexas.edu/files/v2/listings//irplus/data/lrqdata?pretty=true
GET https://vdj-agave-api.tacc.utexas.edu/files/v2/listings//irplus/data/lrqdata
Authorization: Bearer {{tok}}

###




# curl -H "Authorization:Bearer $tok"  https://vdj-agave-api.tacc.utexas.edu/files/v2/listings//irplus/data/lrqdata?pretty=true
GET https://vdj-agave-api.tacc.utexas.edu/files/v2/listings//irplus/data/lrqdata?pretty=true
Authorization: Bearer {{tok}}
###

# curl -H "Authorization:Bearer $tok"  https://vdj-agave-api.tacc.utexas.edu/files/v2/listings//irplus/data/lrqdata?pretty=true
GET https://vdj-agave-api.tacc.utexas.edu/files/v2/listings//irplus/data/lrqdata?pretty=true
Authorization: Bearer {{tok}}

###


###
GET https://vdj-agave-api.tacc.utexas.edu/files/v2/media/system/data.vdjserver.org//irplus/data/lrqdata/lrq-5fbc2ff50c6684237bca22e3.gz
Authorization: Bearer {{tok}}

###