version: '2'

services:
  beanstalkd-console:
    image: schickling/beanstalkd-console
    container_name: beanstalkd-console
    ports:
      - "2080:2080"
    links:
      - beanstalkd

  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - "11300:11300"
