###
POST http://localhost:8199/meta/v3/v1airr/rearrangement/_lrq
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

{
  "name": "myAggrQuery",
  "queryType": "AGGREGATION",
  "query": [
    {"$match": {"repertoire_id": {"$in": ["978739827430911510-242ac11a-0001-012", "967272264750591510-242ac11a-0001-012","1602908186092376551-242ac11c-0001-012"]}}},
    {"$group": {"_id": "$repertoire_id", "count": {"$sum": "1"}}}
  ],
  "notification": "https://httpbin.org/delay/5"
}
###

###
POST http://localhost:8199/meta/v3/v1airr/rearrangement/_lrq
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

{
  "name": "myQuery",
  "queryType": "SIMPLE",
  "query": [{"repertoire_id": "1841923116114776551-242ac11c-0001-012"}, {"cdr1": 1,"cdr2": 1}],
  "notification": "https://httpbin.org/delay/5"
}
###




##############################################################
#
#    testing compression flag in submission
#
##############################################################

###  testCompression-3.8-1.null
POST http://localhost:8199/meta/v3/v1airr/rearrangement/_lrq
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

{
  "name": "testCompression-3.8-1.null",
  "queryType": "SIMPLE",
  "query": [{"repertoire_id": "1841923116114776551-242ac11c-0001-012"}],
  "notification": "https://httpbin.org/delay/2"
}
###

### testCompression-3.8-1.true
POST http://localhost:8199/meta/v3/v1airr/rearrangement/_lrq
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

{
  "name": "testCompression-3.8-1.true",
  "queryType": "SIMPLE",
  "query": [{"repertoire_id": "1841923116114776551-242ac11c-0001-012"}],
  "notification": "https://httpbin.org/delay/2",
  "compressedOutput": true
}
###

###  testCompression-3.8-1.false
POST http://localhost:8199/meta/v3/v1airr/rearrangement/_lrq
X-JWT-Assertion-vdjserver.org: {{jwt}}
Content-Type: application/json

{
  "name": "testCompression-3.8-1.false",
  "queryType": "SIMPLE",
  "query": [{"repertoire_id": "1841923116114776551-242ac11c-0001-012"}],
  "notification": "https://httpbin.org/delay/2",
  "compressedOutput": false
}
###
